#server:
#  port: 3000
#
#spring:
#  profiles:
#     active: qa
#
#---
#
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Hello@123
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: '"Welcome to the DEV Code Buffer!!"'
#
#---
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Hello@123
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: '"Welcome to the QA Code Buffer!!"'
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Hello@123
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#welcome:
#  message: '"Welcome to the PROD Code Buffer!!"'